services:
  mongodb:
    image: mongo:4.4
    container_name: fastapi_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: davidade
      MONGO_INITDB_ROOT_PASSWORD: aderaldo01
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
